### ISSUE TITLE
Draft Variable Product Syncing Behaviour

### ISSUE THREAD

**Issue by christopherpclarke** [fbtransfer/facebook-for-woocommerce#1815]
Hi,

I am just inquiring about the intended syncing behaviour of draft variable products in this plugin.

Currently, when I set a variable product as a draft the plugin applies the ‘do not sync’ property to the parent product. However, the product’s variations nonetheless sync with Facebook. To prevent these variations syncing with Facebook, I have to apply the do not sync property manually to each of the variations of the variable product.

Is this the intended behaviour of the plugin? It would be much more convenient for the ‘do not sync’ property on the parent product to override the settings of the product’s variations.

Some products on my website have 20 variations. Therefore, it is a time consuming process to set the ‘do not sync’ status on each of the variations rather than just the parent product.

Thank you in advance for your assistance.

**Comment by budzanowski** [comment]
@christopherpclarke thank you for your question.
This actually looks like a bug ( I will mark this as needs investigation ). We will analyse the behaviour and either fix it or provide a clear rationale in the documentation about this.

**Comment by budzanowski** [comment]
I am closing this in favor of https://github.com/fbtransfer/facebook-for-woocommerce/issues/1803.

**Comment by beckily** [comment]
Could you find a solution for this bug?
