### ISSUE TITLE
PHP Deprecated:  Non-static method should not be called statically

### ISSUE THREAD

**Issue by glagonikas** [fbtransfer/facebook-for-woocommerce#1821]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
We sometimes see the following notice in our logs
`PHP Deprecated:  Non-static method WC_Facebookcommerce_Utils::get_variant_option_name() should not be called statically in /home/xxxxxx/public_html/wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php on line 758`

As the notice states, this originates here https://github.com/fbtransfer/facebook-for-woocommerce/blob/2.3.3/includes/fbproduct.php#L758

**Comment by haszari** [comment]
Thanks for reporting this @glagonikas !

**Comment by budzanowski** [comment]
Closed with #1827
