### ISSUE TITLE
Undefined array key error

### ISSUE THREAD

**Issue by WillBrubaker** [fbtransfer/facebook-for-woocommerce#1825]
## 🔎 Isolate the bug

- [x ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
As reported in https://wordpress.org/support/topic/php-warning-after-update-v-2-3-3/

>PHP Warning: Undefined array key 0 in /var/www/html/wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php on line 565

##🚶‍♀️ Steps to reproduce
Presumably try to sync a product to Facebook that hasn't got an image url

## ✔️ Expected behavior
Some logic to check if the value is populated before trying to assign

**Comment by budzanowski** [comment]
I have identified that this happens when the product image is not set but the product has some images in the galery.

**Comment by budzanowski** [comment]
Closed with #1828
